# Select Target Computer 
#
# Please copy this file to Makefile.systype and uncomment your
# system. Don't commit changes to this file unless you add support for
# a new system.
#SYSTYPE="acc-boston"

#SYSTYPE="mvapich-pgi"

#SYSTYPE="acc-swan"

SYSTYPE="swan"

#SYSTYPE="archer"




#SYSTYPE="mvapich-intel"
#SYSTYPE="all-intel"
#SYSTYPE="openmpi-intel"
#SYSTYPE="pgprof"
