#define PERIODIC 
#define PMGRID 512
#define MULTIPLEDOMAINS 4
#define PEANOHILBERT 
#define WALLCLOCK 
#define MYSORT 
#define NO_ISEND_IRECV_IN_DOMAIN 
#define FIX_PATHSCALE_MPI_STATUS_IGNORE_BUG 
#define LONGIDS 
#define DEBUG 
